user_name= input("what is your name?")
user_age= input("what is your age?")
user_age=input("what is your age?+20")
user_surname= input("what is your surname?")
print( "your name is" +user_name + "and you age is"+ user_age + "user age is"+ user_age + "user_surname is"+ user_surname)